# Generated by Django 3.0.8 on 2020-08-15 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200815_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
